API/urls.py
from django.urls import path, include
from .views import ProductoViewset, CategoriaViewset, MarcaViewset
from rest_framework import routers

router = routers.DefaultRouter()

router.register('producto',ProductoViewset)
router.register('categoria',CategoriaViewset)
router.register('marca',MarcaViewset)

#Urls de la API
urlpatterns = [
    path('', include(router.urls)),
]

FERREMAS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import logout_then_login

from django.urls import re_path
from rest_framework_simplejwt.authentication import JWTAuthentication
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

schema_view = get_schema_view(
   openapi.Info(
      title="Ferremas API",
      default_version='v01',
      description="Documentación de la API para Ferremas",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="ni.ceron@duocuc.cl"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
   authentication_classes=[JWTAuthentication],
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    #API SECCION
    path('api/', include('API.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    #APPS SECCION
    path('accounts/', include('django.contrib.auth.urls')),
    path('carro/',include('carro.urls')),
    
    path('logout/', logout_then_login, name='logout'),
    path('producto/', include('producto.urls'), name='producto'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

carro/urls.py
from django.urls import path
from . import views

app_name = "carro"

urlpatterns = [

    path('', views.vista_carro, name='carro'),
    path('agregar/<int:producto_id>',views.agregar_producto, name='agregar'),
    path('confirmar-direccion/', views.confirmar_direccion, name='confirmar_direccion'),
    path('cambiar_direccion/', views.cambiar_direccion, name='cambiar_direccion'),

    path('sumar_producto/<int:producto_id>/',views.sumar_producto, name='sumar_producto'),
    path('eliminar/<int:producto_id>/',views.eliminar_producto, name='eliminar'),
    path('restar/<int:producto_id>',views.restar_producto, name='restar'),
    path('limpiar/',views.limpiar_carro, name='limpiar'),
    path('mis_compras/', views.mis_compras, name='mis_compras'),



    path('retorno/', views.webpay_retorno, name='webpay_retorno'),
]

home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('', views.home, name='home'),
    # session de administrador
    path('administrador/', views.admin, name="administrador"),
    path('eliminar/<id>/', views.eliminar, name="eliminar"),
    path('pedidos', views.admin_pedido, name="pedidos"),
    path('adminapi/', views.admin_api, name="adminapi"),
    path('export/csv/', views.export_pedidos_csv, name='export_pedidos_csv'),
    path('bodega/', views.bodega, name='bodega'),
    path('cambiar_estado_pedido/', views.cambiar_estado_pedido, name='cambiar_estado_pedido'),
    # seccion de usuario
    path('mis_compras/', views.vista_usuario, name='mis_compras'),

    # seccion de contacto
    path('contacto/', views.contacto, name="contacto"),
    path('registro/', views.registro, name='registro'),
    path('salir/', views.salir, name='salir'),
]

producto/urls.py
from django.urls import path
from . import views

app_name = "producto"

urlpatterns = [

    path('categoria/<int:id>', views.productos, name='categoria'),
    path('detalle_producto/<int:id>', views.detalle_producto, name='detalle_producto'),

]

home/models.py
from django.db import models

# Create your models here.

home/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomUser(UserCreationForm):

    class Meta:
        model = User
        fields = ['username','first_name','last_name','email','password1','password2']

home/views.py
from email.header import Header
from django.shortcuts import render, redirect, get_object_or_404
from producto.models import Producto, Categoria, Pedido, DetallePedido, Direccion, Marca
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.conf import settings
from django.contrib import messages
from .forms import CustomUser
from django.contrib.auth import authenticate, login, logout
from django.core.mail import send_mail
from carro.context_processor import importe_total_carro
from carro.carro import Carro
from django.utils.html import strip_tags
import csv
from django.http import HttpResponse
from django.db.models import Q
from django.urls import reverse
# Create your views here.


def home(request):
    productos = Producto.objects.all()
    categorias = Categoria.objects.all()
    

    queryset = request.GET.get('buscar')

    if queryset:
        productos = Producto.objects.filter(
            Q(nombre__icontains=queryset)
        ).distinct()

    data = {
        'productos': productos,
        'categorias': categorias,
        
    }

    return render(request, 'index.html', data)


def admin(request):

    if request.user.is_staff:
    
        productos = Producto.objects.all()
        categorias = Categoria.objects.all()
        marcas = Marca.objects.all()

        data = {
            'productos': productos,
            'categorias': categorias,
            'marcas':marcas
        }


        if request.method != 'POST':
            return render(request, 'administrador/admin.html', data)
        else:
            form_id = request.POST.get('form_id')
            if form_id == 'form-producto':
                imagen = request.FILES.get('imagen')
                if not imagen:
                    imagen = '/producto/default.jpg'
                nombre = request.POST['nombre']
                descipcion = request.POST['desc']
                seccion = request.POST['seccion']
                marca = request.POST['marca-list']
                precio = request.POST['precio']
                stock = request.POST['stock']

                categoria = Categoria.objects.get(nombre=seccion)
                marca = Marca.objects.get(nombre = marca )

                objProducto = Producto.objects.create(
                    imagen=imagen,
                    nombre=nombre,
                    descripcion=descipcion,
                    precio=precio,
                    categoria=categoria,
                    marca = marca,
                    stock = stock,
                )
                objProducto.save()
            elif form_id == 'form-categoria':

                categoria  = request.POST['nueva-categoria']
                objCategoria = Categoria.objects.create(
                    nombre = categoria 
                )

                objCategoria.save()

            elif form_id == 'form-marca':

                marca  = request.POST['nueva-marca']
                objmarca = Marca.objects.create(
                    nombre = marca 
                )

                objmarca.save()
                messages.success(request,'Producto creado correctamente')

            # return redirect(to='admin_page:productos')

            return render(request, 'administrador/admin.html', data)
        
    else:
        return redirect(to='home:home')
    
def admin_pedido(request):
    pedidos = Pedido.objects.all()
    detalles_pedidos = DetallePedido.objects.all()

    pedidos_con_detalles = []

    for p in pedidos:
        detalles = []
        for dp in detalles_pedidos:
            if p.id == dp.pedido_id:
                detalles.append(dp.producto)
            

        pedido = {
            'id': p.id,
            'user': p.user,
            'total': p.total,
            'fecha': p.created_at,
            'direccion':p.direccion,
            'productos': detalles
        }
        pedidos_con_detalles.append(pedido)

    data = {
        'pedidos': pedidos_con_detalles
    }

    return render(request, 'administrador/pedidos_admin.html', data)

def export_pedidos_csv(request):
    # Crear la respuesta con el tipo de contenido CSV
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="pedidos.csv"'

    # Crear un escritor CSV
    writer = csv.writer(response)
    # Escribir el encabezado del CSV
    writer.writerow(['ID', 'Fecha', 'Total','Cliente'])

    # Obtener todos los registros de pedidos y escribirlos en el CSV
    pedidos = Pedido.objects.all()
    for pedido in pedidos:
        writer.writerow([pedido.pk, pedido.created_at, pedido.total, pedido.user])

    return response

def admin_api(request):

    return render(request,'administrador/api_admin.html')


def eliminar(request, id):

    producto = get_object_or_404(Producto, id=id)
    producto.delete()

    return redirect(to='home:administrador')


# seccion de contacto
def contacto(request):

    if request.method =='POST':

        name = request.POST['name']
        email = request.POST['email']
        subject = request.POST['subject']
        message = request.POST['message']

        template = render_to_string('Contacto/email_cointacto.html', {
            'name':name,
            'email':email,
            'message':message
        })

        email = EmailMessage(
            subject,
            template,
            settings.EMAIL_HOST_USER,
            ['nicolas134b@gmail.com']
        )

        email.content_subtype = 'html'

        email.fail_silently = False
        email.send()

        messages.success(request,'Se ha enviado el correo')

        return redirect(to='home:contacto')

        


    return render(request, 'contacto/Contacto.html', )

def registro(request):

    data = {
        'form':CustomUser()
    }

    if request.method == 'POST':
        formulario = CustomUser(data = request.POST)
        if formulario.is_valid():
            formulario.save()
            user = authenticate(username = formulario.cleaned_data["username"], password = formulario.cleaned_data["password1"])
            login(request, user)
            messages.success(request,'Creado correctamente')
            return redirect(to='home:home')
        data["form"] = formulario

    return render(request,'registration/registro.html',data)

def vista_usuario(request):
    total = importe_total_carro(request)
    importe_total = total['importe_total_carro']

    status = request.GET.get('status')

    if status == 'approved':
        direccion_id = request.session.get('direccion_id')
        if direccion_id:
            direccion = Direccion.objects.get(id=direccion_id)
            pedido = Pedido.objects.create(user=request.user, total=importe_total,direccion=direccion)
            del request.session['direccion_id']
        else:
            pedido = Pedido.objects.create(user=request.user, total=importe_total,direccion_id=11)

        carro = Carro(request)
        compra = [
            DetallePedido(
                user=request.user,
                producto_id=key,
                pedido=pedido,
                cantidad=value['cantidad'],
            ) for key, value in carro.carro.items()
        ]

        DetallePedido.objects.bulk_create(compra)

        enviar_mail(
            pedido=pedido,
            detalle_pedido=compra,
            nombreusuario=request.user.username,
            emailusuario=request.user.email,
            total=importe_total_carro(request)
        )

        # Redirige a la misma página sin parámetros
        return redirect(reverse('home:mis_compras'))

    pedidos = Pedido.objects.filter(user=request.user)
    detalles = DetallePedido.objects.filter(user=request.user)

    data = {
        'pedidos': pedidos,
        'detalle_pedidos': detalles,
        'status': status if status else 'No existe ninguna pago'
    }

    return render(request, 'usuario/mis_compras.html', data)

def salir(request):
    logout(request)
    return redirect(to='home:home')

from django.core.mail import EmailMessage


"""
def enviar_mail(**kwargs):
    asunto = 'Gracias por el pedido'

    ctx = {
        'pedido': kwargs.get('pedido'),
        'detalle_pedido': kwargs.get('detalle_pedido'),
        'nombreusuario': kwargs.get('nombreusuario'),
        'total': kwargs.get('total'),
    }

    mensaje_html = render_to_string('usuario/pedido.html', ctx)
    mensaje_texto = strip_tags(mensaje_html)
    
    email = EmailMessage(
        asunto,
        mensaje_html,
        'antoniobarraza1133@gmail.com',
        [kwargs.get('emailusuario')],
    )
    email.content_subtype = 'html'
    email.encoding = 'utf-8'  # 🔐 evita UnicodeEncodeError con ñ, tildes, emojis
    email.send(fail_silently=False)
"""


def enviar_mail(**kwargs):
    print("🧪 Correo simulado: no se envió nada.")


    

def bodega(request):

    pedidos = Pedido.objects.all()

    detalle = DetallePedido.objects.all()

    queryset = request.GET.get('buscar-pedido')

    if queryset:
        pedidos = Pedido.objects.filter(
            Q(id__icontains=queryset),
        ).distinct()

    data = {
        'pedidos' : pedidos,
        'detalle' : detalle
    }

    return render(request,'bodega/bodega.html', data)

def cambiar_estado_pedido(request):
    if request.method == 'POST':
        pedido_id = request.POST.get('pedido_id')
        nuevo_estado = request.POST.get('select-estado')
        pedido = get_object_or_404(Pedido, id=pedido_id)
        pedido.estado = nuevo_estado
        pedido.save()
    return redirect('home:bodega')

home/templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="#">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/categorias.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
</head>

<!-- Sticky Footer layout -->


<!-- Header -->
<nav class="navbar navbar-expand-lg navbar-custom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home:home' %}">
            <img src="{% static 'imagenes/logo_ferre.jpg' %}" alt="Logo" width="50px">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link active" href="{% url 'home:home' %}">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'home:contacto' %}">Contacto</a></li>
                <li class="nav-item">
                    <a class="nav-link" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button">Categorias</a>
                </li>
            </ul>

            {% if user.is_authenticated %}
            <div class="dropdown me-3">
                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown">
                    <i class="fa-solid fa-user"></i> {{ user | upper }}
                    {% if request.user.is_staff %}(STAFF){% endif %}
                </button>
                <ul class="dropdown-menu">
                    {% for u in user.groups.all %}
                        {% if u.name == "bodega" %}
                        <li><a class="dropdown-item" href="{% url 'home:bodega' %}">Bodega</a></li>
                        {% endif %}
                        {% if u.name == "contabilidad" %}
                        <li><a class="dropdown-item" href="{% url 'home:pedidos' %}">Contabilidad</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if request.user.is_superuser %}
                    <li><a class="dropdown-item" href="{% url 'home:administrador' %}">Administrador</a></li>
                    {% endif %}
                    <li><a class="dropdown-item" href="{% url 'home:mis_compras' %}">Mis Compras</a></li>
                    <li><a class="dropdown-item" href="{% url 'home:salir' %}">Cerrar sesión</a></li>
                </ul>
            </div>
            {% else %}
            <a href="{% url 'login' %}" class="btn btn-dark me-3">Iniciar sesión</a>
            {% endif %}

            <a href="{% url 'carro:carro' %}" class="btn btn-dark">
                <i class="fa-solid fa-cart-shopping"></i> Carro
                <span class="badge bg-dark text-white ms-1 rounded-pill">{{ cantidad_total_carro }}</span>
            </a>
        </div>
    </div>
</nav>

<!-- Offcanvas Categorías -->
<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title">Categorías</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas"></button>
    </div>
    <div class="offcanvas-body">
        {% for categoria in categorias %}
        <div class="mt-3">
            <a class="d-block text-decoration-none fw-bold text-dark" href="{% url 'producto:categoria' categoria.id %}">
                {{ categoria.nombre }}
            </a>
        </div>
        {% endfor %}
    </div>
</div>

<!-- Contenido principal -->
<main class="p-5 flex-grow-1">
    {% block content %}
    {% endblock content %}
</main>

<!-- Footer -->
<footer class="mt-auto bg-dark text-white py-4">
    <div class="container-fluid">
        <div class="row p-3">
            <div class="col-xs-12 col-md-6 col-lg-3">
                <img src="{% static 'imagenes/logo_ferre.jpg' %}" alt="Logo" width="120px">
            </div>
            <div class="col-xs-12 col-md-6 col-lg-3">
                <h5>Social</h5>
                <a class="nav-link" href="https://www.facebook.com/profile.php?id=100091678300845">Facebook</a>
                <a class="nav-link" href="https://www.instagram.com/tallerrayomcqeen">Instagram</a>
                <a class="nav-link" href="https://twitter.com/?lang=es">Twitter</a>
            </div>
            <div class="col-xs-12 col-md-6 col-lg-3">
                <h5>Documentos</h5>
                <a class="nav-link" href="terminosycondiciones.html">Términos y condiciones</a>
                <a class="nav-link" href="politicadeprivacidad.html">Políticas de privacidad</a>
                <a class="nav-link" href="#">Garantía</a>
            </div>
            <div class="col-xs-12 col-md-6 col-lg-3">
                <h5>Contáctanos</h5>
                <a class="nav-link" href="#">Fono: +56911111111111</a>
                <a class="nav-link" href="#">Ferre+.cl</a>
            </div>
            <div class="text-center mt-3">
                <p>&copy; All rights reserved 2025</p>
            </div>
        </div>
    </div>
</footer>

<!-- Scripts -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/8cdff4000b.js" crossorigin="anonymous"></script>

</body>
</html>

home/templates/index.html
{%extends 'base.html'%}
{% load static %}
{% block content %}

<head>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>

{% for u in user.groups.all %}

<p>{{u.name}}</p>

{% endfor %}

<!--todo| CARRUSEL PRINCIPAL |-->
<div id="carouselExampleInterval" class="carousel slide mt-3" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active" data-bs-interval="5000">
            <img src="{% static 'imagenes/aaaa.jpg' %}" class="d-block w-100 img-fluid" alt="...">
        </div>
        <div class="carousel-item" data-bs-interval="5000">
            <img src="{% static 'imagenes/eee.jpg' %}" class="d-block w-100 img-fluid" alt="...">
        </div>
        <div class="carousel-item " data-bs-interval="5000">
            <img src="{% static 'imagenes/ppp.jpg' %}" class="d-block w-100 img-fluid" alt="...">
        </div>
        <div class="carousel-item " data-bs-interval="5000">
            <img src="{% static 'imagenes/uu.jpg' %}" class="d-block w-100 img-fluid" alt="...">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

<!--todo| fin de carrucel-->



<!--todo| Titulo de la pagina-->
<div class="text-center p-5">
    <h1>Productos</h1>
</div>

{{result}}

<!--todo| Busqueda-->

<!--Busqueda-->
<div class="row justify-content-center mb-5">
    <div class="col-lg-9">
        <form action="" method="get">
            <div id="busqueda">
                <div class="input-group col-md-12">
                    <input type="text" class="form-control" placeholder="Buscar..." name="buscar">
                    <span class="input-group-btn">
                        <i class="icon icon-search"></i>
                        <button type="submit" class="btn btn-success"><i class="fa-solid fa-magnifying-glass"></i></button>
                    </span>
                </div>
            </div>
        </form>
    </div>
</div>


<!--todo| Seccion de Productos |-->
<div class="row justify-content-center">
    {% for i in productos %}


    <div class="col-md-3 m-3">
        <div class="card rounded-2 shadow" style="position: relative;">
            <!-- <span class="discount-badge">30%</span> -->
            <a href="{% url 'producto:detalle_producto' i.id %}">
                {% if i.imagen %}
                <img src="{{i.imagen.url}}" class="card-img-top" alt="...">
                {% else %}
                <img src="media/producto/default.jpg" class="card-img-top" alt="...">
                {% endif %}
            </a>
            <div class="card-body">
                <h5 class="card-title">{{i.nombre}}</h5>
                <p class="card-text">{{i.marca}}</p>
                <p class="h4">CLP {{i.precio}}</p>
                <a href="{% url 'carro:agregar' i.id %}" class="btn btn-outline-primary btn-block">Añadir al carro <i
                        class="fa-solid fa-cart-shopping"></i></a>
            </div>
        </div>
    </div>

    {% endfor %}
</div>

<script src="{% static 'js/carrito.js' %}"></script>

{% if messages %}
{% for m in messages %}
<script>
    Swal.fire({
        'title': 'Hecho',
        'text': '{{m}}',
        'icon': '{{m.tags}}'
    })
</script>
{% endfor %}
{% endif %}


{% endblock content %}