API/urls.py
from django.urls import path, include
from .views import ProductoViewset, CategoriaViewset, MarcaViewset
from rest_framework import routers

router = routers.DefaultRouter()

router.register('producto',ProductoViewset)
router.register('categoria',CategoriaViewset)
router.register('marca',MarcaViewset)

#Urls de la API
urlpatterns = [
    path('', include(router.urls)),
]

FERREMAS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import logout_then_login

from django.urls import re_path
from rest_framework_simplejwt.authentication import JWTAuthentication
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

schema_view = get_schema_view(
   openapi.Info(
      title="Ferremas API",
      default_version='v01',
      description="Documentación de la API para Ferremas",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="ni.ceron@duocuc.cl"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
   authentication_classes=[JWTAuthentication],
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    #API SECCION
    path('api/', include('API.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    #APPS SECCION
    path('accounts/', include('django.contrib.auth.urls')),
    path('carro/',include('carro.urls')),
    
    path('logout/', logout_then_login, name='logout'),
    path('producto/', include('producto.urls'), name='producto'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('', views.home, name='home'),
    # session de administrador
    path('administrador/', views.admin, name="administrador"),
    path('eliminar/<id>/', views.eliminar, name="eliminar"),
    path('pedidos', views.admin_pedido, name="pedidos"),
    path('adminapi/', views.admin_api, name="adminapi"),
    path('export/csv/', views.export_pedidos_csv, name='export_pedidos_csv'),
    path('bodega/', views.bodega, name='bodega'),
    path('cambiar_estado_pedido/', views.cambiar_estado_pedido, name='cambiar_estado_pedido'),
    # seccion de usuario
    path('mis_compras/', views.vista_usuario, name='mis_compras'),

    # seccion de contacto
    path('contacto/', views.contacto, name="contacto"),
    path('registro/', views.registro, name='registro'),
    path('salir/', views.salir, name='salir'),
]

home/models.py
from django.db import models

# Create your models here.

home/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomUser(UserCreationForm):

    class Meta:
        model = User
        fields = ['username','first_name','last_name','email','password1','password2']

home/views.py
from email.header import Header
from django.shortcuts import render, redirect, get_object_or_404
from producto.models import Producto, Categoria, Pedido, DetallePedido, Direccion, Marca
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.conf import settings
from django.contrib import messages
from .forms import CustomUser
from django.contrib.auth import authenticate, login, logout
from django.core.mail import send_mail
from carro.context_processor import importe_total_carro
from carro.carro import Carro
from django.utils.html import strip_tags
import csv
from django.http import HttpResponse
from django.db.models import Q
from django.urls import reverse
# Create your views here.


def home(request):
    productos = Producto.objects.all()
    categorias = Categoria.objects.all()
    

    queryset = request.GET.get('buscar')

    if queryset:
        productos = Producto.objects.filter(
            Q(nombre__icontains=queryset)
        ).distinct()

    data = {
        'productos': productos,
        'categorias': categorias,
        
    }

    return render(request, 'index.html', data)


def admin(request):

    if request.user.is_staff:
    
        productos = Producto.objects.all()
        categorias = Categoria.objects.all()
        marcas = Marca.objects.all()

        data = {
            'productos': productos,
            'categorias': categorias,
            'marcas':marcas
        }


        if request.method != 'POST':
            return render(request, 'administrador/admin.html', data)
        else:
            form_id = request.POST.get('form_id')
            if form_id == 'form-producto':
                imagen = request.FILES.get('imagen')
                if not imagen:
                    imagen = '/producto/default.jpg'
                nombre = request.POST['nombre']
                descipcion = request.POST['desc']
                seccion = request.POST['seccion']
                marca = request.POST['marca-list']
                precio = request.POST['precio']
                stock = request.POST['stock']

                categoria = Categoria.objects.get(nombre=seccion)
                marca = Marca.objects.get(nombre = marca )

                objProducto = Producto.objects.create(
                    imagen=imagen,
                    nombre=nombre,
                    descripcion=descipcion,
                    precio=precio,
                    categoria=categoria,
                    marca = marca,
                    stock = stock,
                )
                objProducto.save()
            elif form_id == 'form-categoria':

                categoria  = request.POST['nueva-categoria']
                objCategoria = Categoria.objects.create(
                    nombre = categoria 
                )

                objCategoria.save()

            elif form_id == 'form-marca':

                marca  = request.POST['nueva-marca']
                objmarca = Marca.objects.create(
                    nombre = marca 
                )

                objmarca.save()
                messages.success(request,'Producto creado correctamente')

            # return redirect(to='admin_page:productos')

            return render(request, 'administrador/admin.html', data)
        
    else:
        return redirect(to='home:home')
    
def admin_pedido(request):
    pedidos = Pedido.objects.all()
    detalles_pedidos = DetallePedido.objects.all()

    pedidos_con_detalles = []

    for p in pedidos:
        detalles = []
        for dp in detalles_pedidos:
            if p.id == dp.pedido_id:
                detalles.append(dp.producto)
            

        pedido = {
            'id': p.id,
            'user': p.user,
            'total': p.total,
            'fecha': p.created_at,
            'direccion':p.direccion,
            'productos': detalles
        }
        pedidos_con_detalles.append(pedido)

    data = {
        'pedidos': pedidos_con_detalles
    }

    return render(request, 'administrador/pedidos_admin.html', data)

def export_pedidos_csv(request):
    # Crear la respuesta con el tipo de contenido CSV
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="pedidos.csv"'

    # Crear un escritor CSV
    writer = csv.writer(response)
    # Escribir el encabezado del CSV
    writer.writerow(['ID', 'Fecha', 'Total','Cliente'])

    # Obtener todos los registros de pedidos y escribirlos en el CSV
    pedidos = Pedido.objects.all()
    for pedido in pedidos:
        writer.writerow([pedido.pk, pedido.created_at, pedido.total, pedido.user])

    return response

def admin_api(request):

    return render(request,'administrador/api_admin.html')


def eliminar(request, id):

    producto = get_object_or_404(Producto, id=id)
    producto.delete()

    return redirect(to='home:administrador')


# seccion de contacto
def contacto(request):

    if request.method =='POST':

        name = request.POST['name']
        email = request.POST['email']
        subject = request.POST['subject']
        message = request.POST['message']

        template = render_to_string('Contacto/email_cointacto.html', {
            'name':name,
            'email':email,
            'message':message
        })

        email = EmailMessage(
            subject,
            template,
            settings.EMAIL_HOST_USER,
            ['nicolas134b@gmail.com']
        )

        email.content_subtype = 'html'

        email.fail_silently = False
        email.send()

        messages.success(request,'Se ha enviado el correo')

        return redirect(to='home:contacto')

        


    return render(request, 'contacto/Contacto.html', )

def registro(request):

    data = {
        'form':CustomUser()
    }

    if request.method == 'POST':
        formulario = CustomUser(data = request.POST)
        if formulario.is_valid():
            formulario.save()
            user = authenticate(username = formulario.cleaned_data["username"], password = formulario.cleaned_data["password1"])
            login(request, user)
            messages.success(request,'Creado correctamente')
            return redirect(to='home:home')
        data["form"] = formulario

    return render(request,'registration/registro.html',data)

def vista_usuario(request):
    total = importe_total_carro(request)
    importe_total = total['importe_total_carro']

    status = request.GET.get('status')

    if status == 'approved':
        direccion_id = request.session.get('direccion_id')
        if direccion_id:
            direccion = Direccion.objects.get(id=direccion_id)
            pedido = Pedido.objects.create(user=request.user, total=importe_total,direccion=direccion)
            del request.session['direccion_id']
        else:
            pedido = Pedido.objects.create(user=request.user, total=importe_total,direccion_id=11)

        carro = Carro(request)
        compra = [
            DetallePedido(
                user=request.user,
                producto_id=key,
                pedido=pedido,
                cantidad=value['cantidad'],
            ) for key, value in carro.carro.items()
        ]

        DetallePedido.objects.bulk_create(compra)

        enviar_mail(
            pedido=pedido,
            detalle_pedido=compra,
            nombreusuario=request.user.username,
            emailusuario=request.user.email,
            total=importe_total_carro(request)
        )

        # Redirige a la misma página sin parámetros
        return redirect(reverse('home:mis_compras'))

    pedidos = Pedido.objects.filter(user=request.user)
    detalles = DetallePedido.objects.filter(user=request.user)

    data = {
        'pedidos': pedidos,
        'detalle_pedidos': detalles,
        'status': status if status else 'No existe ninguna pago'
    }

    return render(request, 'usuario/mis_compras.html', data)

def salir(request):
    logout(request)
    return redirect(to='home:home')

from django.core.mail import EmailMessage


"""
def enviar_mail(**kwargs):
    asunto = 'Gracias por el pedido'

    ctx = {
        'pedido': kwargs.get('pedido'),
        'detalle_pedido': kwargs.get('detalle_pedido'),
        'nombreusuario': kwargs.get('nombreusuario'),
        'total': kwargs.get('total'),
    }

    mensaje_html = render_to_string('usuario/pedido.html', ctx)
    mensaje_texto = strip_tags(mensaje_html)
    
    email = EmailMessage(
        asunto,
        mensaje_html,
        'antoniobarraza1133@gmail.com',
        [kwargs.get('emailusuario')],
    )
    email.content_subtype = 'html'
    email.encoding = 'utf-8'  # 🔐 evita UnicodeEncodeError con ñ, tildes, emojis
    email.send(fail_silently=False)
"""


def enviar_mail(**kwargs):
    print("🧪 Correo simulado: no se envió nada.")


    

def bodega(request):

    pedidos = Pedido.objects.all()

    detalle = DetallePedido.objects.all()

    queryset = request.GET.get('buscar-pedido')

    if queryset:
        pedidos = Pedido.objects.filter(
            Q(id__icontains=queryset),
        ).distinct()

    data = {
        'pedidos' : pedidos,
        'detalle' : detalle
    }

    return render(request,'bodega/bodega.html', data)

def cambiar_estado_pedido(request):
    if request.method == 'POST':
        pedido_id = request.POST.get('pedido_id')
        nuevo_estado = request.POST.get('select-estado')
        pedido = get_object_or_404(Pedido, id=pedido_id)
        pedido.estado = nuevo_estado
        pedido.save()
    return redirect('home:bodega')

home/templates/administrador/api_admin.html
{% extends 'administrador/base_administrador.html' %}


{% load static %}
{% block content %}

<div id="page-content-wrapper">

    <!-- * Boton-->

    <nav class="navbar navbar-expand-lg navbar-light bg-transparent py-4 px-4">
        <div class="d-flex align-items-center">
            <i class="fas fa-align-left primary-text fs-4 me-3" id="menu-toggle"></i>
            <h2 class="fs-2 m-0">API</h2>
        </div>
    </nav>

    <!-- * CONTENIDO PAGINA*-->

    <div class="container-fluid px-4 ">


        <div class="p-4" style="background-color: white;">
            <div class="container mt-4">
                <h2 class="text-center">Documentación de la API</h2>
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Acceso a la API de Ferre+ (Solo para Administradores)</h5>
                                <p class="card-text">
                                    Para probar nuestra API, necesitas un Access Token que tiene una validez de un día. 
                                    Este token se utiliza para autenticar y autorizar tus solicitudes a la API.
                                </p>
                                <p class="card-text">
                                    <strong>Pasos para obtener y utilizar el Access Token:</strong>
                                </p>
                                <ol>
                                    <li>Solicita un Access Token a través del punto final de autenticación.</li>
                                    <li>Usa el Access Token en el encabezado de autorización de tus solicitudes API.</li>
                                    <li>El token expira después de 24 horas, momento en el cual necesitarás obtener uno nuevo.</li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="p-2 mt-4" style="background-color: white;">
            <div class="container mt-4">
                <h2 class="text-center">Obtención del token</h2>
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Generar Access Token</h5>
                                <div class="mt-3">
                                    <input type="text" id="username" class="form-control" placeholder="Usuario">
                                    <input type="password" id="password" class="form-control mt-2" placeholder="Contraseña">
                                    <button id="generateTokenBtn" class="btn btn-primary mt-2" onclick="generateToken()">Generar Access Token</button>
                                </div>
                                <div class="mt-3">
                                    <input type="text" id="accessToken" class="form-control" readonly placeholder="Tu Access Token aparecerá aquí">
                                    <button class="btn btn-secondary mt-2" onclick="copyToken()">Copiar Token</button>
                                </div>
                                <a href="{% url 'schema-swagger-ui' %}" class="btn btn-primary mt-3" target="_blank">Probar API en Swagger</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>

<script src="{% static 'js/api.js' %}"></script>
    
{% endblock content %}


    

home/templates/administrador/base_administrador.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css">


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}" />
    <title> {% block title %} Dashboard {% endblock %} </title>
    <link rel="shortcut icon" href="{% static 'imagenes/instrumentos.jpg' %}" type="image/x-icon">
</head>

<body>
    <div class="d-flex" id="wrapper">
        <!-- Sidebar -->


        {% if user.is_superuser %}

        <div class="" id="sidebar-wrapper" style="background-color: black;">
            <div class="sidebar-heading text-center py-4 primary-text fs-4 fw-bold text-uppercase border-bottom"><a
                    href="#">
                    <img src="{% static 'imagenes/ferre.jpg' %}" alt="" width="200px" height="165">
                </a></div>
            <div class="list-group list-group-flush my-3">
                <a href="{% url 'home:home' %}"
                    class="list-group-item list-group-item-action bg-transparent second-text">
                    <i class="fa-solid fa-desktop me-2"></i>Ir a la pagina</a>


                <a href="{% url 'home:administrador' %}" class="list-group-item list-group-item-action bg-transparent second-text 
                                {% if request.path == '/administrador/' %} active {% endif %}">
                    <i class="fa-solid fa-tag me-2"></i>Productos</a>

                <a href="{% url 'home:pedidos' %}" class="list-group-item list-group-item-action bg-transparent second-text 
                        {% if request.path == '/pedidos' %} active {% endif %}">
                    <i class="fa-solid fa-receipt me-2"></i>Pedidos</a>


                <a href="{% url 'home:bodega' %}" class="list-group-item list-group-item-action bg-transparent second-text 
                        {% if request.path == '/bodega/' %} active {% endif %}">
                    <i class="fa-solid fa-dolly me-2"></i>Bodega</a>


                <a href="{% url 'home:adminapi' %}" class="list-group-item list-group-item-action bg-transparent second-text 
                        {% if request.path == '/adminapi/' %} active {% endif %}">
                    <i class="fa-solid fa-network-wired me-2"></i>API</a>


                <a href="#" onclick="cerrarSesion()"
                    class="list-group-item list-group-item-action bg-transparent text-danger "><i
                        class="fas fa-power-off me-2"></i>Cerrar Sesion</a>

            </div>
        </div>

        {% endif %}


        {% for u in user.groups.all %}
        {% if u.name == "bodega" %}

        <div class="" id="sidebar-wrapper" style="background-color: black;">
            <div class="sidebar-heading text-center py-4 primary-text fs-4 fw-bold text-uppercase border-bottom"><a
                    href="#">
                    <img src="{% static 'imagenes/ferre.jpg' %}" alt="" width="200px" height="165">
                </a></div>
            <div class="list-group list-group-flush my-3">
                <a href="{% url 'home:home' %}"
                    class="list-group-item list-group-item-action bg-transparent second-text">
                    <i class="fa-solid fa-desktop me-2"></i>Ir a la pagina</a>


                <a href="{% url 'home:bodega' %}" class="list-group-item list-group-item-action bg-transparent second-text 
                    {% if request.path == '/bodega/' %} active {% endif %}">
                    <i class="fa-solid fa-dolly me-2"></i>Bodega</a>


                <a href="#" onclick="cerrarSesion()"
                    class="list-group-item list-group-item-action bg-transparent text-danger "><i
                        class="fas fa-power-off me-2"></i>Cerrar Sesion</a>

            </div>
        </div>
        {% endif %}
        {% endfor %}

        {% for u in user.groups.all %}
        {% if u.name == "contabilidad" %}

        <div class="" id="sidebar-wrapper" style="background-color: black;">
            <div class="sidebar-heading text-center py-4 primary-text fs-4 fw-bold text-uppercase border-bottom"><a
                    href="#">
                    <img src="{% static 'imagenes/ferre.jpg' %}" alt="" width="200px" height="165">
                </a></div>
            <div class="list-group list-group-flush my-3">
                <a href="{% url 'home:home' %}"
                    class="list-group-item list-group-item-action bg-transparent second-text">
                    <i class="fa-solid fa-desktop me-2"></i>Ir a la pagina</a>


                <a href="{% url 'home:pedidos' %}" class="list-group-item list-group-item-action bg-transparent second-text 
                    {% if request.path == '/pedidos' %} active {% endif %}">
                    <i class="fa-solid fa-receipt me-2"></i>Pedidos</a>


                <a href="#" onclick="cerrarSesion()"
                    class="list-group-item list-group-item-action bg-transparent text-danger "><i
                        class="fas fa-power-off me-2"></i>Cerrar Sesion</a>

            </div>
        </div>
        {% endif %}

        {% endfor %}



        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->


        <div id="page-content-wrapper" style="background-color:#eeeeee;">
            {% block content %}


            {% endblock %}
        </div>
    </div>
    <!-- /#page-content-wrapper -->
    </div>

    <!--* JS Globales *-->
    <!--Importar jquery-->
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <!--JS DE BOOSTRAP-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"></script>
    <!--FontAwesome-->
    <script src="https://kit.fontawesome.com/8cdff4000b.js" crossorigin="anonymous"></script>
    <!--SwetAlert-->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    {% if messages %}
    {% for m in messages %}
    <script>
        Swal.fire({
            'title': 'Echo',
            'text': '{{m}}',
            'icon': '{{m.tags}}'
        })
    </script>
    {% endfor %}
    {% endif %}

    <script>
        function cerrarSesion() {

            Swal.fire({
                title: 'Estas seguro?',
                text: "Saldras de tu cuenta",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                cancelButtonText: 'Cancelar',
                confirmButtonText: 'Si, Salir!',
                reverseButtons: true
            }).then((result) => {
                if (result.isConfirmed) {
                    window.location = ('/salir/')

                }
            })

        }
    </script>
    <!--* /JS Globales *-->
    <script>
        var el = document.getElementById("wrapper");
        var toggleButton = document.getElementById("menu-toggle");
        toggleButton.onclick = function () {
            el.classList.toggle("toggled");
        };
    </script>

    {% block js %}

    {% endblock %}


</body>

</html>

home/templates/administrador/pedidos_admin.html
{% extends 'administrador/base_administrador.html' %}

{% load static %}

{% block title %} Productos {% endblock %}

{% block content %}


<div id="page-content-wrapper">

    <!-- * Boton-->

    <nav class="navbar navbar-expand-lg navbar-light bg-transparent py-4 px-4">
        <div class="d-flex align-items-center">
            <i class="fas fa-align-left primary-text fs-4 me-3" id="menu-toggle"></i>
            <h2 class="fs-2 m-0">Pedidos</h2>
        </div>
    </nav>

    <!-- * CONTENIDO PAGINA*-->

    <div class="container-fluid px-4 ">


        <div class="p-2" style=" background-color: white;">


            <!--todo BOTONES (ENCABEZADO)-->
            <div class="m-3">
                <a href="{% url 'home:export_pedidos_csv' %}" class="btn btn-primary">Descargar CSV</a>


            </div>

            <!--todo TABLA (CUERPO)-->

            <div class="col table-responsive p-3 rounded">

                <table class="table table-striped text-center shadow">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th class="col">Usuario</th>
                            <th class="col">Fecha de pedido</th>
                            <th class="col">Direccion</th>
                            <th class="col">Productos</th>
                            <th class="col">Total</th>
                        </tr>
                    </thead>

                    <tbody>

                        {% if pedidos %}
                        {% for i in pedidos %}
                        <tr>
                            <td class="col">{{i.id}}</td>
                            <td class="col">$ {{i.user}}</td>
                            <td class="col">{{i.fecha}}</td>
                            <td class="col">
                                <strong>Region: </strong> {{i.direccion.region}} <br>
                                <strong>Comuna:</strong>  {{i.direccion.comuna}} <br>
                                <strong>Calle:</strong> {{i.direccion.calle}}
                            </td>
                            <td class="col">
                                
                                {% for p in i.productos %}
                                    <ul>
                                        <li>
                                            {{p}}
                                        </li>
                                    </ul>
                                {% endfor %}
                                    

                            </td>
                            <td class="col">{{i.total}}</td>
                        </tr>
                        {% endfor %}
                        {% else %}
                        <td colspan="8">Ningun producto creado</td>
                        {% endif %}
                    </tbody>

                </table>
            </div>

            <div>
            </div>
        </div>


    </div>

</div>



{% endblock %}