API/urls.py
from django.urls import path, include
from .views import ProductoViewset, CategoriaViewset, MarcaViewset
from rest_framework import routers

router = routers.DefaultRouter()

router.register('producto',ProductoViewset)
router.register('categoria',CategoriaViewset)
router.register('marca',MarcaViewset)

#Urls de la API
urlpatterns = [
    path('', include(router.urls)),
]

FERREMAS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import logout_then_login

from django.urls import re_path
from rest_framework_simplejwt.authentication import JWTAuthentication
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

schema_view = get_schema_view(
   openapi.Info(
      title="Ferremas API",
      default_version='v01',
      description="Documentación de la API para Ferremas",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="ni.ceron@duocuc.cl"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
   authentication_classes=[JWTAuthentication],
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    #API SECCION
    path('api/', include('API.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    #APPS SECCION
    path('accounts/', include('django.contrib.auth.urls')),
    path('carro/',include('carro.urls')),
    
    path('logout/', logout_then_login, name='logout'),
    path('producto/', include('producto.urls'), name='producto'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('', views.home, name='home'),
    # session de administrador
    path('administrador/', views.admin, name="administrador"),
    path('eliminar/<id>/', views.eliminar, name="eliminar"),
    path('pedidos', views.admin_pedido, name="pedidos"),
    path('adminapi/', views.admin_api, name="adminapi"),
    path('export/csv/', views.export_pedidos_csv, name='export_pedidos_csv'),
    path('bodega/', views.bodega, name='bodega'),
    path('cambiar_estado_pedido/', views.cambiar_estado_pedido, name='cambiar_estado_pedido'),
    # seccion de usuario
    path('mis_compras/', views.vista_usuario, name='mis_compras'),

    # seccion de contacto
    path('contacto/', views.contacto, name="contacto"),
    path('registro/', views.registro, name='registro'),
    path('salir/', views.salir, name='salir'),
]

home/models.py
from django.db import models

# Create your models here.

home/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomUser(UserCreationForm):

    class Meta:
        model = User
        fields = ['username','first_name','last_name','email','password1','password2']

home/views.py
from email.header import Header
from django.shortcuts import render, redirect, get_object_or_404
from producto.models import Producto, Categoria, Pedido, DetallePedido, Direccion, Marca
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.conf import settings
from django.contrib import messages
from .forms import CustomUser
from django.contrib.auth import authenticate, login, logout
from django.core.mail import send_mail
from carro.context_processor import importe_total_carro
from carro.carro import Carro
from django.utils.html import strip_tags
import csv
from django.http import HttpResponse
from django.db.models import Q
from django.urls import reverse
# Create your views here.


def home(request):
    productos = Producto.objects.all()
    categorias = Categoria.objects.all()
    

    queryset = request.GET.get('buscar')

    if queryset:
        productos = Producto.objects.filter(
            Q(nombre__icontains=queryset)
        ).distinct()

    data = {
        'productos': productos,
        'categorias': categorias,
        
    }

    return render(request, 'index.html', data)


def admin(request):

    if request.user.is_staff:
    
        productos = Producto.objects.all()
        categorias = Categoria.objects.all()
        marcas = Marca.objects.all()

        data = {
            'productos': productos,
            'categorias': categorias,
            'marcas':marcas
        }


        if request.method != 'POST':
            return render(request, 'administrador/admin.html', data)
        else:
            form_id = request.POST.get('form_id')
            if form_id == 'form-producto':
                imagen = request.FILES.get('imagen')
                if not imagen:
                    imagen = '/producto/default.jpg'
                nombre = request.POST['nombre']
                descipcion = request.POST['desc']
                seccion = request.POST['seccion']
                marca = request.POST['marca-list']
                precio = request.POST['precio']
                stock = request.POST['stock']

                categoria = Categoria.objects.get(nombre=seccion)
                marca = Marca.objects.get(nombre = marca )

                objProducto = Producto.objects.create(
                    imagen=imagen,
                    nombre=nombre,
                    descripcion=descipcion,
                    precio=precio,
                    categoria=categoria,
                    marca = marca,
                    stock = stock,
                )
                objProducto.save()
            elif form_id == 'form-categoria':

                categoria  = request.POST['nueva-categoria']
                objCategoria = Categoria.objects.create(
                    nombre = categoria 
                )

                objCategoria.save()

            elif form_id == 'form-marca':

                marca  = request.POST['nueva-marca']
                objmarca = Marca.objects.create(
                    nombre = marca 
                )

                objmarca.save()
                messages.success(request,'Producto creado correctamente')

            # return redirect(to='admin_page:productos')

            return render(request, 'administrador/admin.html', data)
        
    else:
        return redirect(to='home:home')
    
def admin_pedido(request):
    pedidos = Pedido.objects.all()
    detalles_pedidos = DetallePedido.objects.all()

    pedidos_con_detalles = []

    for p in pedidos:
        detalles = []
        for dp in detalles_pedidos:
            if p.id == dp.pedido_id:
                detalles.append(dp.producto)
            

        pedido = {
            'id': p.id,
            'user': p.user,
            'total': p.total,
            'fecha': p.created_at,
            'direccion':p.direccion,
            'productos': detalles
        }
        pedidos_con_detalles.append(pedido)

    data = {
        'pedidos': pedidos_con_detalles
    }

    return render(request, 'administrador/pedidos_admin.html', data)

def export_pedidos_csv(request):
    # Crear la respuesta con el tipo de contenido CSV
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="pedidos.csv"'

    # Crear un escritor CSV
    writer = csv.writer(response)
    # Escribir el encabezado del CSV
    writer.writerow(['ID', 'Fecha', 'Total','Cliente'])

    # Obtener todos los registros de pedidos y escribirlos en el CSV
    pedidos = Pedido.objects.all()
    for pedido in pedidos:
        writer.writerow([pedido.pk, pedido.created_at, pedido.total, pedido.user])

    return response

def admin_api(request):

    return render(request,'administrador/api_admin.html')


def eliminar(request, id):

    producto = get_object_or_404(Producto, id=id)
    producto.delete()

    return redirect(to='home:administrador')


# seccion de contacto
def contacto(request):

    if request.method =='POST':

        name = request.POST['name']
        email = request.POST['email']
        subject = request.POST['subject']
        message = request.POST['message']

        template = render_to_string('Contacto/email_cointacto.html', {
            'name':name,
            'email':email,
            'message':message
        })

        email = EmailMessage(
            subject,
            template,
            settings.EMAIL_HOST_USER,
            ['nicolas134b@gmail.com']
        )

        email.content_subtype = 'html'

        email.fail_silently = False
        email.send()

        messages.success(request,'Se ha enviado el correo')

        return redirect(to='home:contacto')

        


    return render(request, 'contacto/Contacto.html', )

def registro(request):

    data = {
        'form':CustomUser()
    }

    if request.method == 'POST':
        formulario = CustomUser(data = request.POST)
        if formulario.is_valid():
            formulario.save()
            user = authenticate(username = formulario.cleaned_data["username"], password = formulario.cleaned_data["password1"])
            login(request, user)
            messages.success(request,'Creado correctamente')
            return redirect(to='home:home')
        data["form"] = formulario

    return render(request,'registration/registro.html',data)

def vista_usuario(request):
    total = importe_total_carro(request)
    importe_total = total['importe_total_carro']

    status = request.GET.get('status')

    if status == 'approved':
        direccion_id = request.session.get('direccion_id')
        if direccion_id:
            direccion = Direccion.objects.get(id=direccion_id)
            pedido = Pedido.objects.create(user=request.user, total=importe_total,direccion=direccion)
            del request.session['direccion_id']
        else:
            pedido = Pedido.objects.create(user=request.user, total=importe_total,direccion_id=11)

        carro = Carro(request)
        compra = [
            DetallePedido(
                user=request.user,
                producto_id=key,
                pedido=pedido,
                cantidad=value['cantidad'],
            ) for key, value in carro.carro.items()
        ]

        DetallePedido.objects.bulk_create(compra)

        enviar_mail(
            pedido=pedido,
            detalle_pedido=compra,
            nombreusuario=request.user.username,
            emailusuario=request.user.email,
            total=importe_total_carro(request)
        )

        # Redirige a la misma página sin parámetros
        return redirect(reverse('home:mis_compras'))

    pedidos = Pedido.objects.filter(user=request.user)
    detalles = DetallePedido.objects.filter(user=request.user)

    data = {
        'pedidos': pedidos,
        'detalle_pedidos': detalles,
        'status': status if status else 'No existe ninguna pago'
    }

    return render(request, 'usuario/mis_compras.html', data)

def salir(request):
    logout(request)
    return redirect(to='home:home')

from django.core.mail import EmailMessage


"""
def enviar_mail(**kwargs):
    asunto = 'Gracias por el pedido'

    ctx = {
        'pedido': kwargs.get('pedido'),
        'detalle_pedido': kwargs.get('detalle_pedido'),
        'nombreusuario': kwargs.get('nombreusuario'),
        'total': kwargs.get('total'),
    }

    mensaje_html = render_to_string('usuario/pedido.html', ctx)
    mensaje_texto = strip_tags(mensaje_html)
    
    email = EmailMessage(
        asunto,
        mensaje_html,
        'antoniobarraza1133@gmail.com',
        [kwargs.get('emailusuario')],
    )
    email.content_subtype = 'html'
    email.encoding = 'utf-8'  # 🔐 evita UnicodeEncodeError con ñ, tildes, emojis
    email.send(fail_silently=False)
"""


def enviar_mail(**kwargs):
    print("🧪 Correo simulado: no se envió nada.")


    

def bodega(request):

    pedidos = Pedido.objects.all()

    detalle = DetallePedido.objects.all()

    queryset = request.GET.get('buscar-pedido')

    if queryset:
        pedidos = Pedido.objects.filter(
            Q(id__icontains=queryset),
        ).distinct()

    data = {
        'pedidos' : pedidos,
        'detalle' : detalle
    }

    return render(request,'bodega/bodega.html', data)

def cambiar_estado_pedido(request):
    if request.method == 'POST':
        pedido_id = request.POST.get('pedido_id')
        nuevo_estado = request.POST.get('select-estado')
        pedido = get_object_or_404(Pedido, id=pedido_id)
        pedido.estado = nuevo_estado
        pedido.save()
    return redirect('home:bodega')

home/templates/bodega/bodega.html
{% extends 'administrador/base_administrador.html' %}


{% load static %}
{% block content %}

<div id="page-content-wrapper">

    <!-- * Boton-->

    <nav class="navbar navbar-expand-lg navbar-light bg-transparent py-4 px-4">
        <div class="d-flex align-items-center">
            <i class="fas fa-align-left primary-text fs-4 me-3" id="menu-toggle"></i>
            <h2 class="fs-2 m-0">Bodega</h2>
        </div>
    </nav>

    <!-- * CONTENIDO PAGINA*-->

    <div class="container-fluid px-4 ">

        <div class="p-4" style="background-color: white;">

            <h3>Pedidos</h3>

            <div class="col table-responsive p-3 rounded">

                <!--Busqueda-->
                <div class="row mb-5">
                    <div class="col-lg-5">
                        <form action="" method="get">
                            <div id="busqueda">
                                <div class="input-group col-md-12">
                                    <input type="text" class="form-control" placeholder="ID" name="buscar-pedido">
                                    <span class="input-group-btn">
                                        <i class="icon icon-search"></i>
                                        <button type="submit" class="btn btn-success"><i
                                                class="fa-solid fa-magnifying-glass"></i></button>
                                    </span>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                <table class="table table-striped text-center shadow">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th class="col">Usuario</th>
                            <th class="col">Fecha de pedido</th>
                            <th class="col">Direccion</th>
                            <th class="col">Productos</th>
                            <th class="col">Total</th>
                            <th class="col">Estado actual</th>
                            <th class="col">Cambiar estado</th>
                        </tr>
                    </thead>

                    <tbody>

                        {% if pedidos %}
                        {% for i in pedidos %}
                        <tr>
                            <td class="col">{{i.id}}</td>
                            <td class="col">{{i.user.first_name}} {{i.user.last_name}}</td>
                            <td class="col">{{i.created_at}}</td>
                            <td class="col">
                                <strong>Region: </strong> {{i.direccion.region}} <br>
                                <strong>Comuna:</strong> {{i.direccion.comuna}} <br>
                                <strong>Calle:</strong> {{i.direccion.calle}} <br>
                                <strong>Numero:</strong> {{i.direccion.numero}}
                            </td>
                            <td class="col">

                                {% for d in detalle %}
                                    
                                    {% if d.pedido.id == i.id %}

                                    <ul>
                                        <li>
                                            {{d.producto}} X {{d.cantidad}}
                                        </li>
                                    </ul>
                                        
                                    {% endif %}
                                        
                                {% endfor %}


                            </td>
                            <td class="col">{{i.total}}</td>

                            {% if i.estado ==  0 %}
                                <td class="col bg-primary text-white">{{i.estado_display}}</td>
                            {% endif %}

                            {% if i.estado ==  1 %}
                                <td class="col bg-warning text-black">{{i.estado_display}}</td>
                            {% endif %}
                            
                            {% if i.estado ==  2 %}
                                <td class="col bg-success text-light">{{i.estado_display}}</td>
                            {% endif %}
                                
                            <td class="col">
                                <button onclick="abrirModalCambioEstado({{ i.id }})" type="button"
                                    class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                    <i class="fa-regular fa-pen-to-square"></i>
                                </button>
                            </td>
                        </tr>
                        {% endfor %}
                        {% else %}
                        <td colspan="8">Ningun producto creado</td>
                        {% endif %}
                    </tbody>

                </table>
            </div>



        </div>


    </div>


</div>






</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Cambiar estado</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="{% url 'home:cambiar_estado_pedido' %}" method="post" id="form-estado">
                {% csrf_token %}
                <div class="modal-body">

                    <input type="hidden" name="pedido_id" id="pedido_id">

                    <label for="formGroupExampleInput" class="form-label mt-2">Estado</label>
                    <select class="form-select" aria-label="Default select example" name="select-estado">
                        <option selected value="0">En preparacion</option>
                        <option value="1">En camino</option>
                        <option value="2">Entregado</option>
                    </select>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Cambiar estado</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    function abrirModalCambioEstado(pedidoId) {
        document.getElementById('pedido_id').value = pedidoId;
        var modal = new bootstrap.Modal(document.getElementById('exampleModal'));
        modal.show();
    }
</script>

{% endblock content %}